### ISSUE TITLE
Bits of Sprite move (Or disappear) when text bubble pops up.

### ISSUE THREAD

**Issue by Owai-Seek** [quotefox/Hyper-Station-13#102]
## Reproduction:

(Possibly?) have your sprite scaled to be larger or smaller.
Speak
Poof, no nose.

![dreamseeker_qwN3mnlWfl](https://user-images.githubusercontent.com/7543955/69713907-63feac80-10d3-11ea-9bdd-00c005dce22f.png)

(I'm also pretty sure I've seen someone with prescription glasses "winking". One eye was bigger than the other and when they talked it would "wink".

**Comment by Kraseo** [comment]
auto-fit resolution can be very wonky. did you try this using other settings (32x32, 64x64, 96x96)?

**Comment by Owai-Seek** [comment]
I can confirm that this happens on 64 x 64

**Comment by Owai-Seek** [comment]
![dreamseeker_oMiGB5U7Tf](https://user-images.githubusercontent.com/7543955/69837448-e6df4e80-121c-11ea-8ce0-0ff532bf63c5.png)
![dreamseeker_NPYpJLrZa6](https://user-images.githubusercontent.com/7543955/69837450-e941a880-121c-11ea-9c7d-0c2caa962e71.png)

Comparison. Still 64x64, unsure of their character settings but I've seen it on others too.

**Comment by Dahlular** [comment]
can't really recreate, and this is an old issue. closing; if it reoccurs, make this again with more details.
