### ISSUE TITLE
White Jumpsuit is bugged/doesn't have a sprite.

### ISSUE THREAD

**Issue by CupOfExplodium** [quotefox/Hyper-Station-13#1078]
Issue reported from  Round ID: 5140 (Hyper Station 13)

Reporting client version: 513

![asdasdasdasdas](https://user-images.githubusercontent.com/68045693/115339937-656ac200-a16b-11eb-8090-83b70ffecae6.png)

**Comment by CupOfExplodium** [comment]
CORRECTION, all jumpsuits are broken on me, this is post cloning

**Comment by Dahlular** [comment]
You'd have a much better time reporting these things on the discord; as for this issue, this is just byond being a royal pain in the ass. Reconnecting fixes missing sprites.
