### ISSUE TITLE
Miscellanous suggestions

### ISSUE THREAD

**Issue by jbox144** [quotefox/Hyper-Station-13#119]
I did place the suggestion on discord but most likely it's been lost in the wave of messages since then.

- Breasts should increase in size slightly when arroused (due to milk production)
- The amount of product produced from filling containers should scale with the size of the target bodypart
- Oversized private parts should not immediately tear off clothing. The time taken to tear should be dependent on the size of the private (so that you can go on EVA despite being massive tiddy and then have your spacesuit explode half way through)
- Clothing worn by a player with oversized private parts should damage the clothing until it tears off
- Some clothing is more resistant to oversized private parts, such as stripper gear, maid costumes, so on, and as such have more size capacity than other clothes, take more time to tear, and take less damage while over capacity
- Add some ability to fill containers using other players
- Oversized private parts should cause a small amount of brute damage overtime to the player
- specialised "bras" and "boxers", coming in various sizes (and eventually bluespace) which allow the wearer to wear clothing on their outer layer even when it would normally tear, provided that the bra or boxer is a high enough grade to handle it. These items can be made or bought.
- Milking breasts should reduce their size for a short while.
- The size of the breast and penis sprite should be infinitely scalable.

Reasons.

**Comment by shellspeed1** [comment]
This is for bugs and issues, not code suggestions.
