### ISSUE TITLE
Some PP Types have layering issues.

### ISSUE THREAD

**Issue by Owai-Seek** [quotefox/Hyper-Station-13#1346]
## Round ID:

Unknown - 7/8/21

## Reproduction:

Hemi, Knotted Hemi, and Tapered all have a similar layering issue. They all show through the body (when facing "away".

![dreamseeker_8tWDJ5Ay7c](https://user-images.githubusercontent.com/7543955/124964611-38ea7780-dfef-11eb-9583-502a812c4c51.png)
![dreamseeker_7rUUvE4muW](https://user-images.githubusercontent.com/7543955/124964630-3daf2b80-dfef-11eb-85d0-85bc0f2f883e.png)

**Comment by Dahlular** [comment]
Please report on the discord if you want any issues resolved.
