### ISSUE TITLE
aurora caelus doesn't work

### ISSUE THREAD

**Issue by AtlasRules** [quotefox/Hyper-Station-13#136]
## Round ID: 1145
aurora caelus randomly triggered, yet there was no visual difference.

**Comment by MarkSuckerberg** [comment]
I'd wager starlight is disabled in the config since it's disabled by default

**Comment by LetterN** [comment]
what @MarkSuckerberg said, it's possibly a config thing

**Comment by Dahlular** [comment]
fixed (supposedly), it's indeed a config option
