### ISSUE TITLE
Moth Markings

### ISSUE THREAD

**Issue by SlashSlingingSlasher** [quotefox/Hyper-Station-13#1475]
Issue reported from  Round ID: 6361 (Hyper Station 13)

Reporting client version: 514

Moth Markings will be cleared to none, after a round end, if the character is selected.

**Comment by Dahlular** [comment]
You'll have a higher chance of getting this noticed and dealt with if you report it on the Discord instead.

**Comment by SlashSlingingSlasher** [comment]
I'll try to keep that in mind, my Discord is really broken for me, and has been for quite some time, It takes hours to load a single Discord, and notifications never work.
