### ISSUE TITLE
Xeno digi legs missing

### ISSUE THREAD

**Issue by Crominum** [quotefox/Hyper-Station-13#355]
## Round ID: 

N/A

## Reproduction:

Creating a xeno character with digitigrade legs and the "xeno" and "plain" species markings causes the legs not to appear. 

![3675eff96c7da9019e2b84215e151561](https://user-images.githubusercontent.com/6243123/88877135-d4c20f80-d1f2-11ea-9ab5-7c1fa2ccb0d5.png)

## Additional Notes:

There also seems to be a strange marking from the sprites as well, noticed by the weird L shape jetting from the torso. This shows up on other sprites.

**Comment by Shadow-Quill** [comment]
Fixed in #429

**Comment by The-Sun-In-Splendour** [comment]
@Crominum Close this please
@Shadow-Quill If you do any more PRs involving fixing issues you can place the issue # (#355 for this one) inside the PR so it auto closes the issue

**Comment by The-Sun-In-Splendour** [comment]
> 
> 
> @Crominum Close this please
> @Shadow-Quill If you do any more PRs involving fixing issues you can place the issue # (#355 for this one) inside the PR so it auto closes the issue
