### ISSUE TITLE
Xeno ladder issue. 

### ISSUE THREAD

**Issue by Moltovz** [quotefox/Hyper-Station-13#401]
Having a ladder connect xeno and the mining base gives players free access without having to go Via shuttle, or have ANY mining access. This route is easily gamer-able. This is great for people who don't want to mine, and that one dude in in maint with the gas mask, but no one else. if actual miners want to access the xenarceo base, they can just walk to arivals.
## I still feel like the ladder removes the point of the public mining drop zone

**Comment by VladinXXV** [comment]
I think the _**whole point**_ of that was to have a public mining dock that people could access without mining access. Anything is "gamer-able" given a determined "gamer."

**Comment by Moltovz** [comment]
> I think the _**whole point**_ of that was to have a public mining dock that people could access without mining access. Anything is "gamer-able" given a determined "gamer."

The point of the xenarch base was to be a public/casual mining area. If miners want the crew to access the normal lavaland Z-level they can throw a beacon down.

**Comment by Crashtest-LXXXIX** [comment]
the changes discussed here have now been mapped by me
