### ISSUE TITLE
The stutter from Social Anxiety quirk passes on to desk announcements.

### ISSUE THREAD

**Issue by lyricalpaws** [quotefox/Hyper-Station-13#762]
## Reproduction:
Have a stutter from social anxiety, and make an announcement using one of the requests consoles at a heads's desk. An example using telecomms admin desk on pubbystation: https://paws.aaw.ooo/qtscqc.png

**Comment by quotefox** [comment]
Working as intended right? because announcements are your player's voice, not a robotic one that reads out your messages.
