### ISSUE TITLE
teleporting bread unable to interact with once dead

### ISSUE THREAD

**Issue by MalricB** [quotefox/Hyper-Station-13#909]
## Reproduction:

once the bread is dead you cannot interact with it at all via left click
AKA
can't pick it up / drag it / examine.
can only right click menu it
PR in question: https://github.com/quotefox/Hyper-Station-13/pull/902

**Comment by ArchieBeepBoop** [comment]
Fixed in https://github.com/quotefox/Hyper-Station-13/pull/911

**Comment by MalricB** [comment]
based and breadpilled
